//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace getMatch.worldCupServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMatch", Namespace="http://tempuri.org/", ItemName="match")]
    [System.SerializableAttribute()]
    public class ArrayOfMatch : System.Collections.Generic.List<getMatch.worldCupServer.match> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="match", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ifreturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string homeCourtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string visitingCourtField;
        
        private System.DateTime timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ifreturn {
            get {
                return this.ifreturnField;
            }
            set {
                if ((this.ifreturnField.Equals(value) != true)) {
                    this.ifreturnField = value;
                    this.RaisePropertyChanged("ifreturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string homeCourt {
            get {
                return this.homeCourtField;
            }
            set {
                if ((object.ReferenceEquals(this.homeCourtField, value) != true)) {
                    this.homeCourtField = value;
                    this.RaisePropertyChanged("homeCourt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string visitingCourt {
            get {
                return this.visitingCourtField;
            }
            set {
                if ((object.ReferenceEquals(this.visitingCourtField, value) != true)) {
                    this.visitingCourtField = value;
                    this.RaisePropertyChanged("visitingCourt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="worldCupServer.worldCupSoap")]
    public interface worldCupSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 team 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMatch", ReplyAction="*")]
        getMatch.worldCupServer.getMatchResponse getMatch(getMatch.worldCupServer.getMatchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMatch", Namespace="http://tempuri.org/", Order=0)]
        public getMatch.worldCupServer.getMatchRequestBody Body;
        
        public getMatchRequest() {
        }
        
        public getMatchRequest(getMatch.worldCupServer.getMatchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMatchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string team;
        
        public getMatchRequestBody() {
        }
        
        public getMatchRequestBody(string team) {
            this.team = team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMatchResponse", Namespace="http://tempuri.org/", Order=0)]
        public getMatch.worldCupServer.getMatchResponseBody Body;
        
        public getMatchResponse() {
        }
        
        public getMatchResponse(getMatch.worldCupServer.getMatchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMatchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public getMatch.worldCupServer.ArrayOfMatch getMatchResult;
        
        public getMatchResponseBody() {
        }
        
        public getMatchResponseBody(getMatch.worldCupServer.ArrayOfMatch getMatchResult) {
            this.getMatchResult = getMatchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface worldCupSoapChannel : getMatch.worldCupServer.worldCupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class worldCupSoapClient : System.ServiceModel.ClientBase<getMatch.worldCupServer.worldCupSoap>, getMatch.worldCupServer.worldCupSoap {
        
        public worldCupSoapClient() {
        }
        
        public worldCupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public worldCupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public worldCupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public worldCupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getMatch.worldCupServer.getMatchResponse getMatch.worldCupServer.worldCupSoap.getMatch(getMatch.worldCupServer.getMatchRequest request) {
            return base.Channel.getMatch(request);
        }
        
        public getMatch.worldCupServer.ArrayOfMatch getMatch(string team) {
            getMatch.worldCupServer.getMatchRequest inValue = new getMatch.worldCupServer.getMatchRequest();
            inValue.Body = new getMatch.worldCupServer.getMatchRequestBody();
            inValue.Body.team = team;
            getMatch.worldCupServer.getMatchResponse retVal = ((getMatch.worldCupServer.worldCupSoap)(this)).getMatch(inValue);
            return retVal.Body.getMatchResult;
        }
    }
}
